spring.application.name=book-tracker
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.hobatckiotnngdodwpnv&password=hwy67$vRG(&6

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect